company_address:
  name: Larkin LLC
  raw_line_1: 1505 S BLOUNT ST
  city: RALEIGH
  state: NC
  zip_code: 27603
  country: US
delivery_shifts:
  -
    - Morning
    - M
  -
    - Afternoon
    - A
  -
    - Evening
    - E
